# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Sanal makine için Ubuntu 22.04 imajını kullan
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "iot-gitlab-server"

  # Sanallaştırma sağlayıcısı olarak VirtualBox'ı yapılandır
  config.vm.provider "virtualbox" do |vb|
    # Kullanıcının belirttiği yüksek kaynakları ayarla
    vb.memory = "20480" # 20GB RAM
    vb.cpus = "8"       # 8 CPU
    vb.name = "InceptionOfThings-Bonus"
  end

  # Gerekli port yönlendirmeleri
  # 8443: GitLab Arayüzü (HTTPS)
  # 8888: Örnek Uygulama
  # 8081: Argo CD Arayüzü
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  # Proje klasörünü sanal makine içindeki /vagrant dizinine senkronize et
  config.vm.synced_folder ".", "/vagrant", disabled: false

  # Sanal makine oluşturulduktan sonra kurulum betiğini çalıştır
  config.vm.provision "shell", path: "scripts/setup.sh"
end
