apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/peler1nl1kelt0s/inception-of-things.git
    targetRevision: HEAD
    path: p3/manifests/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

