apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-app-from-local-gitlab
  namespace: argocd
spec:
  project: default
  source:
    # BU SATIR KURULUM BETİĞİ TARAFINDAN OTOMATİK GÜNCELLENECEKTİR
    repoURL: http://root:X7HQY%2FYU1WCoULlTWv%2FQ0tomESvOWcGeTONTLdL2I1A%3D@172.17.0.1:8080/root/iot-project-app.git
    targetRevision: HEAD
    # Kök dizindeki tüm YAML'ları izle
    path: confs/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true