apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
spec:
  type: NodePort
  selector:
    app: wil-playground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30080