# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "mdiragaS" do |mdiragaS|
    mdiragaS.vm.box = "debian/bullseye64"
    mdiragaS.vm.hostname = "mdiragaS"

    mdiragaS.vm.network "private_network", ip: "192.168.56.110"

    mdiragaS.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
    end

    mdiragaS.vm.provision "shell", path: "scripts/setup_k3s.sh"
  end
end