Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |v|

    v.memory = 1024 # 1 GB RAM
    v.cpus = 1      # 1 CPU
  end

  config.vm.define "mdiragaS" do |server|

    server.vm.hostname = "mdiragaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |v|
      v.name = "mdiragaS"
    end

    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  config.vm.define "mdiragaSW" do |worker|

    worker.vm.hostname = "mdiragaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.name = "mdiragaSW"
    end
    
    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end