Vagrant.configure("2") do |config|
  team_login = "museker"
  
  config.vm.box = "generic/debian12"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 512
  end

  config.vm.define "#{team_login}S" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.name = "#{team_login}S"
    end
    server.vm.hostname = "#{team_login}S"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provision "shell", path: "scripts/install-server.sh"
  end

  config.vm.define "#{team_login}SW" do |worker|
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "#{team_login}SW"
    end
    worker.vm.hostname = "#{team_login}SW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provision "shell", path: "scripts/install-worker.sh"
  end
end
