Vagrant.configure("2") do |config|
  config.vm.define "musekerS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "musekerS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "musekerS"
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install-server.sh"
  end

  config.vm.define "musekerSW" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "musekerSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "musekerSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/install-worker.sh"
  end
end

