# bonus/Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.network "forwarded_port", guest: 30080, host: 8888
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "12288"  # En az 8 GB RAM ! 8192
    vb.cpus = "4"       # En az 4 CPU
  end

  config.vm.provision "shell", path: "scripts/setup.sh"
end