# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "iot-gitlab-server"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "20480" 
    vb.cpus = "8"       
    vb.name = "iot-bonus"
  end

  # Port yönlendirmeleri
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true  # GitLab
  config.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true  # Uygulama
  config.vm.network "forwarded_port", guest: 8081, host: 8081, auto_correct: true  # Argo CD
  config.vm.network "forwarded_port", guest: 6443, host: 6443, auto_correct: true  # Kubernetes API
  config.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true  # Registry
  config.vm.network "forwarded_port", guest: 2222, host: 2222, auto_correct: true  # SSH

  config.vm.synced_folder ".", "/vagrant", disabled: false
  
  config.vm.provision "shell", inline: "cd /vagrant/scripts && chmod +x *.sh && ./setup.sh"
end