apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-app-gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.56.10/root/iot-app.git
    targetRevision: HEAD
    path: p3/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true