# =================================================================
# GitLab için Düzeltilmiş ve Tam Yapılandırma Dosyası
# =================================================================

global:
  appConfig:
    externalUrl: http://gitlab.local:8080

  # Host ve domain ayarları. Port numarası BURADA OLMAMALIDIR.
  hosts:
    domain: gitlab.local
    gitlab:
      name: gitlab.local

  # Ingress ayarları. HTTPS'nin kapalı olduğunu belirtiyoruz.
  ingress:
    tls:
      enabled: false
    configureCertmanager: false
  
  # HTTPS'nin global olarak kapalı olduğunu teyit etmek en iyi pratiktir.
  https:
    enabled: false

# =================================================================
# Servis Yapılandırmaları (Sizin ayarlarınız korunmuştur)
# =================================================================

gitlab:
  kas:
    enabled: false #! TEST ICIN EKLENDI
  webservice:
    ingress:
      enabled: true
      hosts:
        - name: gitlab.local
          path: /
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "2.5G"
      limits:
        memory: "4G"
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "1.5G"
      limits:
        memory: "2.5G"
  gitaly:
    resources:
      requests:
        cpu: "200m"
        memory: "1G"
  toolbox:
    resources:
      requests:
        cpu: "100m"
        memory: "600M"

postgresql:
  resources:
    requests:
      cpu: "200m"
      memory: "1G"

redis:
  resources:
    requests:
      cpu: "100m"
      memory: "400M"

# =================================================================
# Diğer Eklentiler (Sizin ayarlarınız korunmuştur)
# =================================================================

nginx-ingress:
  enabled: true

prometheus:
  install: false

gitlab-runner:
  install: false