global:
  hosts:
    domain: gitlab.local
  edition: ce
  ingress:
    configureCertmanager: false
prometheus:
  enabled: false

gitlab-runner:
  enabled: false

nginx-ingress:
  enabled: false

gitlab:
  webservice: { minReplicas: 1, maxReplicas: 1, resources: { requests: { cpu: "150m", memory: "1.2G" } } }
  sidekiq: { minReplicas: 1, maxReplicas: 1, resources: { requests: { cpu: "100m", memory: "800M" } } }
  gitaly: { resources: { requests: { cpu: "100m", memory: "500M" } } }
  postgresql: { resources: { requests: { cpu: "100m", memory: "500M" } } }
  redis: { resources: { cpu: "100m", memory: "200M" } }
  toolbox: { resources: { requests: { cpu: "100m", memory: "400M" } } }