# manifests/deployment/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: wil-playground
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
        component: backend
    spec:
      containers:
      - name: wil-playground-container
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

